language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb
  - sudo dpkg -i bazel_3.1.0-linux-x86_64.deb
  - wget https://github.com/joakimkarlsson/igloo/archive/refs/tags/igloo.1.1.1.zip
  - unzip igloo.1.1.1.zip
  - mv igloo-igloo.1.1.1/igloo /usr/local/include/igloo

script:
  - bazel test //cookiec/test:*
