language: cpp

compiler: g++

os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++-8

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb
  - sudo dpkg -i bazel_3.1.0-linux-x86_64.deb

env:
  - BAZEL_CXXOPTS="-std=c++17"

script:
  - ./cookiec/run.sh tests
