################################################################################
################################ TEST BINARIES #################################
################################################################################

cc_binary(
  name = "Filesystem",
  srcs = [ "fs.cc" ],
  deps = [
    "//cookiec:Filesystem"
  ]
)

cc_binary(
  name = "SourceCodePool",
  srcs = [ "source-code-pool.cc" ],
  deps = [
    "//cookiec:SourceCodePool"
  ]
)

